---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes

- name: Enable nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Upload html file
  ansible.builtin.copy:
    src: "{{ html_file }}"
    dest: "{{ nginx_html_path }}/{{ html_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Template nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/conf.d/hello.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx

